import math as m
import warnings

from rocketpy.exceptions import InvalidParameterError
from rocketpy.mathutils.vector_matrix import Vector
from rocketpy.plots.wire_plots import _WirePlots
from rocketpy.prints.wire_prints import _WirePrints


class Wire:
    """Models the physical characteristics and magnetic field generated by an
    electric wire.

    Calculates the magnetic field generated by a straight, current-carrying
    wire segment at arbitrary spatial points using the Biot-Savart law. Supports
    continuous communication wires and event-based ignition wires (e.g., motor
    ignition, parachute deployment).

    Attributes
    ----------
    Wire.current : float, int
        Intensity of the electric current flowing through the wire in Amperes (A).
    Wire.magnetic_field : dict
        Dictionary of calculated magnetic fields. Keys are position coordinate
        tuples (x, y, z) in the Body Axis Coordinate System, and values
        are the corresponding magnetic field components in Tesla (T).
    Wire.wire_length : float
        Total length of the wire segment in meters.
    Wire.wire_type : str
        Type of wire ("communications" or "ignition").
    Wire.ignition_wire_function : str or None
        Function sub-type when ``wire_type`` is "ignition" ("motor_ignition" or
        "parachute_deployment").
    Wire.extra_ignition_time : float
        Additional duration in seconds for which the ignition current remains
        active after the event trigger.
    Wire.name : str
        Name identifier of the wire.
    """

    def __init__(
        self,
        current: float | int,
        wire_type: str,
        ignition_wire_function: str | None = None,
        extra_ignition_time: float = 0.0,
        name: str = "wire",
    ) -> None:
        """Initializes the Wire class.

        Parameters
        ----------
        current : float, int
            Intensity of the current flowing through the wire in Amperes (A).
            Conventional current flows from the first endpoint to the second
            endpoint defined in the rocket attachment.
        wire_type : str
            Type of wire:

            - "communications": Continuous current, represents continuous data
              or power transmission, generating a steady magnetic field.
            - "ignition": Current is active only during specific deployment or
              ignition events.
        ignition_wire_function : str, optional
            Function of the ignition wire (mandatory if ``wire_type`` is
            "ignition"). Valid options are "motor_ignition" or
            "parachute_deployment". Default is None.
        extra_ignition_time : float, optional
            Additional duration in seconds the ignition current persists
            after event actuation. Default is 0.
        name : str, optional
            Name of the wire. Default is "wire".
        """
        self._validate_parameters(
            current, extra_ignition_time, wire_type, ignition_wire_function
        )
        self._magnetic_field = {}
        self.magnetic_field = {}
        self._wire_endpoints_bacs = []
        self.wire_length = 0.0
        self.parachute_name = None
        self.name = name
        self._csys = None
        self.center_of_dry_mass_position = None

        # prints and plots
        self.prints = _WirePrints(self)
        self.plots = _WirePlots(self)

    def _validate_parameters(
        self, current, extra_ignition_time, wire_type, ignition_wire_function
    ) -> None:
        """Validates input parameters and initializes corresponding attributes."""
        self._validate_wire_type(wire_type, ignition_wire_function)
        self._validate_numbers(current, extra_ignition_time)

    def _validate_wire_type(self, wire_type, ignition_wire_function) -> None:
        """Validates wire categorization and functional role."""
        if isinstance(wire_type, str):
            if wire_type == "communications":
                self.wire_type = "communications"
                self.ignition_wire_function = None
            elif wire_type == "ignition":
                self.wire_type = "ignition"
                if ignition_wire_function is None:
                    raise InvalidParameterError(
                        "The 'ignition_wire_function' parameter is required when 'wire_type' is 'ignition'."
                    )
                if not isinstance(ignition_wire_function, str):
                    raise InvalidParameterError(
                        "'ignition_wire_function' must be a string."
                    )
                self.ignition_wire_function = ignition_wire_function
            else:
                raise InvalidParameterError(
                    "'wire_type' must be either 'communications' or 'ignition'."
                )
        else:
            raise InvalidParameterError("'wire_type' must be a string.")

    def _validate_numbers(self, current, extra_ignition_time) -> None:
        """Validates numerical attributes defining wire physical characteristics."""
        if not isinstance(current, (float, int)):
            raise InvalidParameterError("Current must be a float or int.")
        self.current = float(current)

        if not isinstance(extra_ignition_time, (float, int)):
            raise InvalidParameterError("'extra_ignition_time' must be a float or int.")
        if extra_ignition_time < 0:
            raise InvalidParameterError(
                "'extra_ignition_time' must be greater than or equal to 0."
            )
        self.extra_ignition_time = float(extra_ignition_time)

    def measure_magnetic_field(
        self, position_vector: list | tuple | Vector, frame: str = "ucs"
    ) -> None:
        """Calculates and stores the magnetic field vector at the point given by
        ``position_vector`` in the Body Axis Coordinate System using the finite
        straight-wire Biot-Savart formula.

        Parameters
        ----------
        position_vector : list, tuple, Vector
            Coordinates [x, y, z] in meters in the specified ``frame``
            in which we want to calculate the magnetic field.
        frame : str, optional
            Frame in which the ``position_vector`` is given. It can either be "bacs"
            (body axis coordinate sytem) or "ucs" (user defined coordiante
            system).
        """
        r1 = self._wire_endpoints_bacs[0]  # starting endpoint
        r2 = self._wire_endpoints_bacs[1]  # final end
        l = r2 - r1  # Vector along the wire pointing in direction of current
        self.wire_length = abs(l)

        r_v = self._position_vector_to_bacs(position_vector, frame)
        r_t = tuple(r_v)

        if self.wire_length < 1e-12:
            self.magnetic_field[r_t] = [0.0, 0.0, 0.0]
            self._magnetic_field[r_t] = Vector([0.0, 0.0, 0.0])
            return

        r1_v = r_v - r1
        r2_v = r_v - r2

        cross_l_r1 = l ^ r1_v
        cross_norm = abs(cross_l_r1)

        if cross_norm < 1e-12:
            b_v = Vector([0, 0, 0])
            warnings.warn(
                "'position vector' is collinear with the wire segment; magnetic field is zero.",
                UserWarning,
            )
        else:
            l_unit = l / self.wire_length
            cos_theta1 = l_unit @ r1_v.unit_vector
            cos_theta2 = l_unit @ r2_v.unit_vector

            b_v = (
                (1e-7 * self.current)
                * (cross_l_r1 / (cross_norm**2))
                * (cos_theta1 - cos_theta2)
                * self.wire_length
            )

        self.magnetic_field[r_t] = list(b_v)
        self._magnetic_field[r_t] = b_v

    def _position_vector_to_bacs(
        self,
        position_vector: list | tuple | Vector,
        frame: str = "bacs",
    ) -> Vector:
        """Transforms, if necessary, the position_vector to the BACS frame.

        Parameters
        ----------
        position_vector : list, tuple, Vector
            Coordinates [x, y, z] in meters in the specified ``frame``
            in which we want to calculate the magnetic field.
        frame : str, optional
            Frame in which the ``position_vector`` is given. It can either be "bacs"
            (body axis coordinate system) or "ucs" (user defined coordinate
            system). Default is "ucs".

        Returns
        -------
        position_vector_bacs : Vector
            Vector coordinates [x, y, z] in meters in the BACS frame.
        """
        if not isinstance(frame, str):
            raise InvalidParameterError("'frame' must be a string.")

        frame_lower = frame.lower()
        if frame_lower not in ("ucs", "bacs"):
            raise InvalidParameterError(
                f"Invalid frame '{frame}'. Must be 'ucs' or 'bacs'."
            )
        if isinstance(position_vector, (list, tuple, Vector)):
            pos_v = Vector(position_vector)
        else:
            raise InvalidParameterError(
                "'position_vector' must be a tuple, list, or Vector instance."
            )
        if frame_lower == "bacs":
            position_vector_bacs = pos_v
        else:
            cdm_user_frame = Vector([0, 0, self.center_of_dry_mass_position])
            delta = pos_v - cdm_user_frame
            if self._csys == -1:  # nose to tail
                position_vector_bacs = Vector([-delta[0], delta[1], -delta[2]])
            else:  # tail to nose
                position_vector_bacs = delta

        return position_vector_bacs

    def define_magnetic_field(
        self,
        position_vector: list | tuple | Vector,
        magnetic_field: float | int | list | tuple | Vector,
    ) -> None:
        """Manually sets the magnetic field vector produced by the wire at a
        specified position coordinate.

        Parameters
        ----------
        position_vector : list, tuple, Vector
            Target position coordinates [x, y, z] in meters defined in the
            Body Axis Coordinate System.
        magnetic_field : float, int, list, tuple, Vector
            Magnetic field vector in Tesla (T):

            - If a scalar (float or int), the same field value is assigned
              isotropically across all three axes: [B, B, B].
            - If a 3-element list, tuple, or Vector, sets the directional
              field components [Bx, By, Bz].
        """
        position_vector_t = tuple(position_vector)
        if isinstance(magnetic_field, (float, int)):
            magnetic_field = [magnetic_field, magnetic_field, magnetic_field]
        self._magnetic_field[position_vector_t] = Vector(magnetic_field)
        self.magnetic_field[position_vector_t] = list(magnetic_field)

    def _set_wire_endpoints_to_bacs(
        self,
        rocket,
        _wire_endpoints_from_user_coordinate_system: list[Vector]
        | tuple[Vector, Vector],
    ) -> None:
        """Transforms wire endpoint coordinates from the User-defined Coordinate
        System to the Body Axis Coordinate System and stores them.

        Parameters
        ----------
        rocket : Rocket
            Rocket instance to which the wire is attached.
        _wire_endpoints_from_user_coordinate_system : list[Vector] or tuple[Vector, Vector]
            Sequence containing the two endpoint position vectors in the
            User-defined Coordinate System.
        """
        self._wire_endpoints_bacs = []
        cdm_user_frame = Vector([0, 0, self.center_of_dry_mass_position])
        for endpoint_from_user in _wire_endpoints_from_user_coordinate_system:
            self._check_entry_dimensions(endpoint_from_user, rocket)
            endpoint_from_cdm_user_frame = endpoint_from_user - cdm_user_frame
            if self._csys == -1:  # nose to tail
                endpoint_position_bacs_frame = Vector(
                    [
                        -endpoint_from_cdm_user_frame[0],
                        endpoint_from_cdm_user_frame[1],
                        -endpoint_from_cdm_user_frame[2],
                    ]
                )
            else:  # tail to nose
                endpoint_position_bacs_frame = endpoint_from_cdm_user_frame
            self._wire_endpoints_bacs.append(endpoint_position_bacs_frame)

    def _check_entry_dimensions(self, pt, rocket) -> None:
        """Verifies that an endpoint coordinates lie within the physical rocket.

        Parameters
        ----------
        pt : list, tuple, Vector
            Endpoint coordinates [x, y, z] in the User-defined Coordinate System.
        rocket : Rocket
            Rocket instance in which geometry bounds are verified.
        """
        if not rocket.z_bounds_check(pt[2], frame="ucs")[0]:
            raise InvalidParameterError(
                f"The axial coordinate z = {pt[2]} m of endpoint {pt} is outside the rocket longitudinal bounds."
            )

        if m.hypot(pt[0], pt[1]) > rocket.general_radius(pt[2], frame="ucs"):
            raise InvalidParameterError(
                f"Endpoint {pt} exceeds the rocket fuselage radius at z = {pt[2]} m."
            )

    def _rocket_belonging(self, rocket) -> None:
        """Associates the rocket to which the Wire belongs to the
        _WirePlots instance and defines the center of dry mass
        and the z orientation as a wire attributes.

        Parameters
        ----------
        rocket : Rocket
            Rocket instance to which the wire belongs.
        """
        self._csys = rocket._csys
        self.center_of_dry_mass_position = rocket.center_of_dry_mass_position
        self.plots.rocket = rocket

    def info(self) -> None:
        """Print a summary of the information stored in the wire object."""
        self.prints.all()

    def all_info(self) -> None:
        """Prints all data and graphs available about the Wire."""
        self.plots.all()
        self.prints.all()

    @classmethod
    def from_dict(cls, data: dict) -> "Wire":
        """Creates a Wire instance from a dictionary containing the initialization
        parameters.

        Parameters
        ----------
        data : dict
            Dictionary containing wire constructor attributes.

        Returns
        -------
        wire : Wire
            Wire instance initialized with the specified parameters.
        """
        return cls(
            # Mandatory Parameters
            current=data["current"],
            wire_type=data["wire_type"],
            # Optional Parameters
            ignition_wire_function=data.get("ignition_wire_function", None),
            extra_ignition_time=data.get("extra_ignition_time", 0.0),
            name=data.get("name", "wire"),
        )
