name: Populate Changelog
on:
  pull_request:
    types: [closed]
    branches:
      - develop
jobs:
  self:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RocketPy repository
        uses: actions/checkout@v3
        with:
          repository: Malmahrouqi3/RocketPy-mo2
          ref: changelog-update
          token: ${{ secrets.TOKEN }}

      - name: Update Changelog
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        run: |
          SECTION="### Added"
          PREFIX="ENH"

          if [[ "$PR_LABELS" == *"Bug"* ]]; then
            SECTION="### Fixed"
            PREFIX="BUG"
          elif [[ "$PR_LABELS" == *"Refactor"* ]] || [[ "$PR_LABELS" == *"Maintenance"* ]]; then
            SECTION="### Changed"
            PREFIX="MNT"
          elif [[ "$PR_LABELS" == *"Docs"* ]] && [[ "$PR_LABELS" == *"Git housekeeping"* ]]; then
            SECTION="### Changed"
            PREFIX="DOC"
          elif [[ "$PR_LABELS" == *"Docs"* ]]; then
            # Only documentation -> Added section
            SECTION="### Added"
            PREFIX="DOC"
          elif [[ "$PR_LABELS" == *"Tests"* ]]; then
            SECTION="### Changed"
            PREFIX="TST"
          fi

          ENTRY="- $PREFIX: $PR_TITLE [#$PR_NUMBER](https://github.com/RocketPy-Team/RocketPy/pull/$PR_NUMBER)"
          SECTION_LINE=$(grep -n "^$SECTION$" CHANGELOG.md | head -1 | cut -d: -f1)

          sed -i "${SECTION_LINE}a\\$ENTRY" CHANGELOG.md

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "DOC: Update Changelog for PR #${{ github.event.pull_request.number }}"
          git push
